spring.application.name=wallet-ledger

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=wallet_user
spring.datasource.password=wallet_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
